### ISSUE TITLE
Compatibilitat amb BSD

### ISSUE THREAD

**Issue by evilham** [ConsorciAOC/signador#13]
És impossible signar res amb un sistema BSD.
Realment fa falta que detecteu el sistema operatiu i cancel·leu l'execució?

**Comment by albciff** [comment]
No tens raó... tot i no donar suport explícit, podríem simplement provar de carregar a veure si hi ha sort. M'ho puc revisar, però no prometo res :)

**Comment by evilham** [comment]
Per començar: em disculpo per haver obert aquest issue amb un missatge tan curt i potser xocant.
El contexte és: havia gastat ja dues hores en fer una gestió de 20 minuts i al final he hagut d'arrencar una màquina virtual amb windows per fer servir una qüestió del govern.

Això és el resultat d'executar l'applet:
```
Codebase matches codebase manifest attribute, and application is signed. Continuing. See: http://docs.oracle.com/javase/7/docs/technotes/guides/jweb/security/no_redeploy.html for details.
[OSName] Sistema operatiu: FreeBSD
Current OS: OS not supported :(
[CertSelectionDialog] OS No suportat.
java.lang.RuntimeException: El sistema operatiu no està suportat en el mode keystore_type=0
	at cat.aoc.signador.AplicacioSignatura.sanityCheck(AplicacioSignatura.java:227)
	at cat.aoc.signador.AplicacioSignatura.<init>(AplicacioSignatura.java:208)
	at cat.aoc.signador.AplicacioSignaturaLauncher.main(AplicacioSignaturaLauncher.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:574)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:936)
[javascript] is called: onSignError
java.lang.RuntimeException: El sistema operatiu no està suportat en el mode keystore_type=0
	at cat.aoc.signador.AplicacioSignatura.sanityCheck(AplicacioSignatura.java:227)
	at cat.aoc.signador.AplicacioSignatura.<init>(AplicacioSignatura.java:208)
	at cat.aoc.signador.AplicacioSignaturaLauncher.main(AplicacioSignaturaLauncher.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:574)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:936)
```

L'aplicació "nativa" l'únic que sembla que fa és incloure l'executable de `java`, en el cas del `.sh` és un binari ELF, per Linux, per això tampoc funcionarà en un sistema BSD.

Idealment l'Applet s'integraria amb un Keychain del sistema operatiu (com ho fa en windows i sembla que ho fa amb MacOS) però en una plataforma "no suportada" em permetria triar el fitxer del certificat, demanaria la contrasenya per obrir-lo i faria la signatura; això sí que funcionaria allà on funcioni Java.
Potser això últim ja és el cas, però l'Applet diu: "OS No suportat", indicaria que hi ha algun tipus de comprovació "Si MacOS: fes X, si Windows fes Y, si Linux fes Z, si no 'OS No suportat'".

**Comment by albciff** [comment]
Hola @evilham no cal q et disculpis, entenc perfectament la frustració q comporta passar massa temps fent un tràmit, el problema és que els recursos (i coneixements) que tenim són limitats i desenvolupo altres projectes, per això no podem donar suport a tots els sistemes operatius i triem els de la majoria dels nostres usuaris.

De tota manera has entès perfectament com funciona l'aplicació, i com fa la selecció del magatzem de claus en funció de navegador i sistema operatiu :)

Puc incloure el FreeBSD no em costaria gaire, en cas que detecti aquest sistema operatiu podria actuar com si és tractés d'ubuntu, en el cas d'ubuntu intentem carregar el magatzem de claus de firefox.

Tot i que el tema de carregar un P12 o un altre magatzem de claus de l'usuari en cas de no poder carregar el del sistema operatiu és una bona idea, em suposaria canviar més l'estructura i portaria més temps i no crec q ho duguem a terme. Però si vols el que si que puc fer, és en cas de freebsd o alguns altres sistemes operatius basats en linux es carregar les claus del magatzem de firefox.

Només t'hauries d'instal·lar el firefox i carregar la teva clau al magatzem.

Si et sembla bé podem provar fent aquest canvi.

**Comment by albciff** [comment]
Finalment amb la versió disponible al web -> https://signador.aoc.cat/signador/installNativa es va implementar el intent de suport per a FreeBSD. Disculpeu la terrible demora en respondre.
