### ISSUE TITLE
Problemas en Debian Strecht

### ISSUE THREAD

**Issue by dherchhoren** [ConsorciAOC/signador#14]
Hola.
Soy usuario de Debian Strecht y estoy teniendo problemas para ejecutar Signador, ya que el archivo root generado está incompleto, y el de certificados también.

Este es el archivo de logs generado:

```
log4j:ERROR Could not parse file [log4j.xml].
java.io.FileNotFoundException: /home/diher/Signador/lib/log4j.xml (No existe el fichero o el directorio)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:623)
	at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:148)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:805)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)
	at org.apache.log4j.xml.DOMConfigurator$1.parse(DOMConfigurator.java:749)
	at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:871)
	at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:755)
	at org.apache.log4j.xml.DOMConfigurator.configure(DOMConfigurator.java:896)
	at cat.aoc.app.startup.LoggingConfig.configLog4j(LoggingConfig.java:17)
	at cat.aoc.app.server.Server.main(Server.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:65)
	at com.install4j.runtime.launcher.UnixLauncher.main(UnixLauncher.java:57)
2020-05-26 10:22:44.614:INFO::main: Logging initialized @3195ms
2020-05-26 10:22:45.285:INFO:oejs.Server:main: jetty-9.2.10.v20150310
2020-05-26 10:22:45.429:INFO:oejsh.ContextHandler:main: Started o.e.j.s.ServletContextHandler@49993335{/,null,AVAILABLE}
2020-05-26 10:22:46.181:INFO:oejs.ServerConnector:main: Started ServerConnector@a373588{SSL-http/1.1}{0.0.0.0:9090}
2020-05-26 10:22:46.182:INFO:oejs.Server:main: Started @4780ms

```
¿Qué puede estar ocurriendo?.

**Comment by oriolbernal** [comment]
Buenos días, 

Actualmente esta incidencia debería quedar resulta si se reinstala la aplicación nativa:
https://signador.aoc.cat/signador/installNativa
