### ISSUE TITLE
Problemes amb Debian + Mozilla Firefox

### ISSUE THREAD

**Issue by ismael-benito** [ConsorciAOC/signador#22]
Benvolguts/des,

espero que em pugueu guiar en com solucionar aquest problema, ja que Debian i Ubuntu són molt semblants. Estic encallat amb la següent pantalla:

![image](https://github.com/user-attachments/assets/27aa6dba-103f-4202-8011-154ff82e7e45)

El log del Signador, diu el següent: 

```bash
[OSName] Sistema operatiu: Linux
[MozillaKeyStore] name = NSS0
attributes= compatibility
slot = 2
library = /usr/lib/firefox-esr/libsoftokn3.so
nssArgs = "configdir='/home/ibenito/.mozilla/firefox/dsd1u88n.default' DbMode ='readOnly' certPrefix='' keyPrefix='' secmod='secmod.db' flags=readOnly" 
[OSName] Sistema operatiu: Linux
[MozillaKeyStore] name = NSS1
attributes= compatibility
slot = 2
library = /usr/lib/firefox-esr/libsoftokn3.so
nssArgs = "configdir='/home/ibenito/.mozilla/firefox/vts3pz8r.default-esr' DbMode ='readOnly' certPrefix='' keyPrefix='' secmod='secmod.db' flags=readOnly" 
[OSName] Sistema operatiu: Linux
[CertificateStore] Carreguem el PKCS11 TCAT
No existeix el fitxer :/usr/lib/libaetpkss.so
No existeix el fitxer :/usr/lib/libaetpkss.so.3
No hi ha instal·lada al sistema cap de les llibreries proprocionades
No hi ha instal·lada al sistema cap de les llibreries proporcionades
No s'ha pogut carregar el PKCS11 TCAT
[OSName] Sistema operatiu: Linux
[CertificateStore] Carreguem el PKCS11 TCAT
No existeix el fitxer :/usr/lib/bit4id/libbit4xpki.so
No hi ha instal·lada al sistema cap de les llibreries proprocionades
No hi ha instal·lada al sistema cap de les llibreries proporcionades
No s'ha pogut carregar el PKCS11 TCAT
[OSName] Sistema operatiu: Linux
[CertificateStore] Carreguem el PKCS11 dnie
No existeix el fitxer :/usr/lib/opensc-pkcs11.so
No existeix el fitxer :/usr/local/lib/opensc-pkcs11.so
No existeix el fitxer :/lib/opensc-pkcs11.so
No hi ha instal·lada al sistema cap de les llibreries proprocionades
No hi ha instal·lada al sistema cap de les llibreries proporcionades
No s'ha pogut carregar el PKCS11 dnie
[javascript] is called: onSignError
```

A banda que no reconeix la lectura de targetes, estic intentant fer una signatura pel registre d'una associació i sembla que el repositori de claus de Mozilla Firefox sí que el detecta, que és on tinc instal·lat l'IDCAT.

A veure si algú s'ha trobat en la mateixa situació.

Moltes gràcies,
Isma

**Comment by ismael-benito** [comment]
Confirmo que reprodueixo el mateix problema a Windows.

![Captura de pantalla de 2024-07-21 21-54-50](https://github.com/user-attachments/assets/ca69d263-39ac-48f0-8471-0848f9089dc9)

**Comment by ismael-benito** [comment]
Finalment, la única opció viable després d'invertir unes 4h de mal de cap ha estat Windows + Gestor de Calus de Windows. 

Per si serveix l'error de Windows + Firefox ha estat: 

```bash
22 jul 2024 01:18:17,178 INFO  LoggingConfig  : [MSKeyStore] Iniciant operació d'eliminació de claus 
22 jul 2024 01:18:17,179 INFO  LoggingConfig  : [MSKeyStore] Comprovem si la clau ISMAEL BENITO ALTAMIRANO - DNI 47964799R ha de ser eliminada 
22 jul 2024 01:18:17,179 INFO  LoggingConfig  : [MSKeyStore] Comprovem si la clau ismael.benito@ub.edu ha de ser eliminada 
22 jul 2024 01:18:17,183 INFO  LoggingConfig  : [checkValidityPeriod] Certificate expired or not yet valid: NotAfter: Mon Nov 28 09:45:57 CET 2022
22 jul 2024 01:18:17,183 INFO  LoggingConfig  : org.catcert.crypto.keyStoreImpl.CertificateStoreException: No hi ha certificats disponibles per a signar.
22 jul 2024 01:18:17,184 INFO  LoggingConfig  : 	at org.catcert.crypto.keyStoreImpl.CertificateStore.getSigningCertificates(CertificateStore.java:301)
22 jul 2024 01:18:17,184 INFO  LoggingConfig  : 	at cat.aoc.signador.AplicacioSignatura.getCertificatesFromJS(AplicacioSignatura.java:381)
22 jul 2024 01:18:17,184 INFO  LoggingConfig  : 	at cat.aoc.app.rest.controllers.CertificateService.getCerts(CertificateService.java:48)
22 jul 2024 01:18:17,184 INFO  LoggingConfig  : 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22 jul 2024 01:18:17,184 INFO  LoggingConfig  : 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
22 jul 2024 01:18:17,184 INFO  LoggingConfig  : 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22 jul 2024 01:18:17,184 INFO  LoggingConfig  : 	at java.lang.reflect.Method.invoke(Method.java:498)
22 jul 2024 01:18:17,184 INFO  LoggingConfig  : 	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
22 jul 2024 01:18:17,184 INFO  LoggingConfig  : 	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
22 jul 2024 01:18:17,184 INFO  LoggingConfig  : 	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
22 jul 2024 01:18:17,184 INFO  LoggingConfig  : 	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
22 jul 2024 01:18:17,184 INFO  LoggingConfig  : 	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
22 jul 2024 01:18:17,184 INFO  LoggingConfig  : 	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
22 jul 2024 01:18:17,184 INFO  LoggingConfig  : 	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
22 jul 2024 01:18:17,184 INFO  LoggingConfig  : 	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
22 jul 2024 01:18:17,184 INFO  LoggingConfig  : 	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
22 jul 2024 01:18:17,184 INFO  LoggingConfig  : 	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
22 jul 2024 01:18:17,184 INFO  LoggingConfig  : 	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
22 jul 2024 01:18:17,184 INFO  LoggingConfig  : 	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
22 jul 2024 01:18:17,184 INFO  LoggingConfig  : 	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
22 jul 2024 01:18:17,185 INFO  LoggingConfig  : 	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
22 jul 2024 01:18:17,185 INFO  LoggingConfig  : 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
22 jul 2024 01:18:17,185 INFO  LoggingConfig  : 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
22 jul 2024 01:18:17,185 INFO  LoggingConfig  : 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
22 jul 2024 01:18:17,185 INFO  LoggingConfig  : 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
22 jul 2024 01:18:17,185 INFO  LoggingConfig  : 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
22 jul 2024 01:18:17,185 INFO  LoggingConfig  : 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
22 jul 2024 01:18:17,185 INFO  LoggingConfig  : 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
22 jul 2024 01:18:17,185 INFO  LoggingConfig  : 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
22 jul 2024 01:18:17,185 INFO  LoggingConfig  : 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
22 jul 2024 01:18:17,185 INFO  LoggingConfig  : 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
22 jul 2024 01:18:17,185 INFO  LoggingConfig  : 	at org.eclipse.jetty.server.Server.handle(Server.java:497)
22 jul 2024 01:18:17,185 INFO  LoggingConfig  : 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
22 jul 2024 01:18:17,185 INFO  LoggingConfig  : 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
22 jul 2024 01:18:17,186 INFO  LoggingConfig  : 	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
22 jul 2024 01:18:17,186 INFO  LoggingConfig  : 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
22 jul 2024 01:18:17,186 INFO  LoggingConfig  : 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
22 jul 2024 01:18:17,186 INFO  LoggingConfig  : 	at java.lang.Thread.run(Thread.java:748)
22 jul 2024 01:18:17,186 INFO  LoggingConfig  : [javascript] is called: onSignError
22 jul 2024 01:18:17,614 INFO  LoggingConfig  : [ERROR] Codi: 01;Descripció: No hi ha certificats disponibles per a signar.
22 jul 2024 01:18:17,614 DEBUG CertificateService: [getCerts] Num certs: 0
22 jul 2024 01:18:17,614 INFO  CertificateService: [getCerts] - Fi
```

Que sembla un error diferent del de Linux. 

En fi, molts ànims a qui s'estimbi aquí.

**Comment by dpcat237** [comment]
Tinc Ubuntu 24.04 i em surt el mateix error de que no detecta els certificats. En logs també el mateix
```
No s'ha pogut carregar el PKCS11 dnie
[javascript] is called: onSignError
[ERROR] Codi: 01;Descripció: No hi ha certificats disponibles per a signar.
```

**Comment by furgo16** [comment]
Tinc el mateix problema a Ubuntu 22.04. Sembla ser que intenta carregar les biblioteques per lectors de targetes i no les troba, i ignora totalment el certificat digital. En el meu cas, simplement volia signar un document amb el certificat digital de l'IdCat, i no he pogut.

Al final, he acabat fent servir el programa [Autofirma](https://firmaelectronica.gob.es/Home/Descargas.html), que ha funcionat a la primera i sense complicacions. Fins i tot hi ha paquets d'instaŀlació per a diferents distribucions de Linux

Cal dir que el signador no duu més que problemes:
- Fet amb tecnologies anticuades (script bash, Java per a l'escriptori).
- Instal·lació impossible de fer per a usuaris no avançats (l'instal·lador és un script que cal executar a la línia d'ordres, les instruccions d'instal·lació són complicades fins i tot per a usuaris avançats)
- Cal executar-lo des de la línia d'ordres, i no dóna cap mena de feedback si s'està executant correctament o no. A la documentació no diu enlloc (o bé no ho he pogut trobar) que s'ha de deixar executant en el rerefons. Fins que no he llegit comentaris d'altres usuaris a issues aquí al GitHub, no he entès això. M'ha portat moltes hores intentant analitzar perquè no funcionava
- El codi no s'ha tocat des de fa  3 anys
- Els desenvolupadors no responen aquí al GitHub
- En resum, sembla ser que s'hagi programat i distribuït per a usuaris de Linux dels 90, i ja estem al 2024... De fet, avui dia ni hauria de caldre una aplicació nativa, i s'hauria de poder fer tot aquest procés des del navegador. Trauria molta feina de manteniment i desenvolupament d'aplicacions per a 3 plataformes diferents. I sobretot, no crearia barreres i evitaria maldecaps als usuaris.

Així doncs, continuaré utilitzant l'Autofirma per ara.

En tot cas, per si poden ajudar a algú, aquí teniu un retall de l'informe de l'aplicació quan falla:

```
[OSName] Sistema operatiu: Linux
[CertificateStore] Carreguem el PKCS11 TCAT
No existeix el fitxer :/usr/lib/libaetpkss.so
No existeix el fitxer :/usr/lib/libaetpkss.so.3
No hi ha instal·lada al sistema cap de les llibreries proprocionades
No hi ha instal·lada al sistema cap de les llibreries proporcionades
No s'ha pogut carregar el PKCS11 TCAT
[OSName] Sistema operatiu: Linux
[CertificateStore] Carreguem el PKCS11 TCAT
No existeix el fitxer :/usr/lib/bit4id/libbit4xpki.so
No hi ha instal·lada al sistema cap de les llibreries proprocionades
No hi ha instal·lada al sistema cap de les llibreries proporcionades
No s'ha pogut carregar el PKCS11 TCAT
[OSName] Sistema operatiu: Linux
[CertificateStore] Carreguem el PKCS11 dnie
No existeix el fitxer :/usr/lib/opensc-pkcs11.so
No existeix el fitxer :/usr/local/lib/opensc-pkcs11.so
No existeix el fitxer :/lib/opensc-pkcs11.so
No hi ha instal·lada al sistema cap de les llibreries proprocionades
No hi ha instal·lada al sistema cap de les llibreries proporcionades
No s'ha pogut carregar el PKCS11 dnie
[javascript] is called: onSignError
[ERROR] Codi: 01;Descripció: No hi ha certificats disponibles per a signar.
[AplicacioSignatura] Ignored parameter pdf_reason:=
[AplicacioSignatura] Ignored parameter pdf_location:=
```

**Comment by ismael-benito** [comment]
Em sap greu que us trobeu a situacions similars a la meva. No soc cap desenvolupador d'aquesta eina. Crec que hi ha hagut alguna actualització d'un tercer (probablement Firefox(?)) que fa que no reconegui els certificats instal·lats a Firefox a cap dels sistemes operatius, ja que jo vaig reproduir tant l'error a Debian com a Windows, i vosaltres l'heu trobat a Ubuntu. Teòricament, el cas d'usuari de Windows/Ubuntu + Firefox hauria d'estar suportat. 

Respecte a les targetes d'identitat, no tinc el DNIe activat, i per tant no ho puc testejar. Però, instal·lant els drivers oficials del Ministerio del Interior, a mi se'm van canviar els missatges d'error per una detecció del driver (van desaparèixer els missatges `No hi ha instal·lada al sistema cap de les llibreries proprocionades` ). Així i tot, no ho vaig poder provar com que no tenia cap targeta vàlida. 

Fins ara,
Ismael

**Comment by narcisgarcia** [comment]
**Signador no sembla preparat per a usuaris inexperts.**
He provat amb Debian GNU/Linux i també Windows 10; el procés d'instal·olació i configuració és una mica críptic, especialment al cas de GNU/Linux.
Les diferents opcions què ofereix en el cas de Windows no aclareix quines implicacions tenen (com el tema de M.Firefox).
L'instal·lador tampoc no avisa de què és el què cal fer una vegada instal·lat (reiniciar el navegador, iniciar Signador com a aplicació abans o després...)

I per a completar, tot i què fucnioni la el comprovador de l'aoc.cat (test de signador), després aquest no detecta els certificats de M.Firefox ESR, fins i tot quan ja s'havia iniciat sessió amb certificat del navegador a la «Carpeta ciutadana».

[ismael-benito](https://github.com/ismael-benito) esmentava la possibilitat de què Signador utilitzi la gestió de claus de Windows. COM ES FA?

![Image](https://github.com/user-attachments/assets/13cfcd52-8496-4c79-8d04-0e82a9d2e0c1)

![Image](https://github.com/user-attachments/assets/a8069f42-61a6-4809-9de0-d4799b77e0ad)

![Image](https://github.com/user-attachments/assets/378052a3-5026-4922-9e3b-7c358f9036e6)

**Comment by ismael-benito** [comment]
Bona pregunta, no recordo com ho vaig fer exactament, perquè no soc usuari de Windows habitual des de fa 10 o més anys. El cas és que pots instal·lar certificats al Windows, no al Firefox, sinó al mateix Windows. Suposo que això és correcte: https://suport-idcat.aoc.cat/hc/ca/articles/4417343960337-Com-descarregar-i-instal-lar-l-idCAT-Certificat

Fins ara,
Ismael
