### ISSUE TITLE
Signador no s'obre en Windows

### ISSUE THREAD

**Issue by Imanflow** [ConsorciAOC/signador#23]
Se que es escriure aquí es tant inútil com la maleïda eina aquesta, però al menys ho deixaré per escrit. 

La instal·lació sembla que sigui correcta, però quan s'intenta obrir un arxiu jnlp per signar alguna cosa, no pasa res. El log es el següent:

`log4j:ERROR Could not parse file [log4j.xml].
java.io.FileNotFoundException: C:\Program Files\Signador\lib\log4j.xml (El sistema no puede encontrar el archivo especificado)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:623)
	at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:148)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:806)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:205)
	at org.apache.log4j.xml.DOMConfigurator$1.parse(DOMConfigurator.java:749)
	at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:871)
	at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:755)
	at org.apache.log4j.xml.DOMConfigurator.configure(DOMConfigurator.java:896)
	at cat.aoc.app.startup.LoggingConfig.configLog4j(LoggingConfig.java:17)
	at cat.aoc.app.server.Server.main(Server.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)
`

Així que sembla que la instal·lació no es correcte, pero jódete.

**Comment by orgt-xavierdaviu** [comment]
Hola, nosaltres utilitzem aquesta eina i va molt bé.
La instal·lació és correcta, però per defecte no crea un fitxer de configuració de log4j.xml, per tant l'has de crear tu mateix i posar-lo a la carpeta indicada C:\Program Files\Signador\lib

Per internet hi ha multitud d'exemples de creació d'aquest fitxer, per exemple:
https://java2blog.com/log4j-xml-configuration-example/#4_Create_log4jxml_file

Llavors en el fitxer de log que indiquis en la configuració veuràs tot el procés de signatura i podràs comprovar on us falla.

**Comment by oriolbernal** [comment]
Bon dia,

Podries provar de desinstal·lar i tornar a instal·lar la nativa de 0. 
Aquest problema ja hauria d'estar resolt
